### ISSUE TITLE
Are Native modules supported.

### ISSUE THREAD

**Issue by mauron85** [pmq20/node-compiler#25] opened 2017-05-05 07:26 UTC
Thank you for this amazing compiler.

I tried to compile one of my project which is using [microtime](https://github.com/wadey/node-microtime) native module. I compiled it succesfully, but when I run binary I get following error:

```
/__enclose_io_memfs__/node_modules/node-time-uuid/node_modules/microtime/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /__enclose_io_memfs__/node_modules/node-time-uuid/node_modules/microtime/build/Release/microtime.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/__enclose_io_memfs__/node_modules/node-time-uuid/node_modules/microtime/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/__enclose_io_memfs__/node_modules/node-time-uuid/node_modules/microtime/index.js:1:96)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/__enclose_io_memfs__/node_modules/node-time-uuid/lib/objectid.js:22:17)
```

So my question is. Are native modules supported?

**Comment by Dexus** [comment] 2017-05-05 08:19
I dont know node-compiler but did you nodec run with `--npm-package=node-time-uuid` ?
Maybe you need compile native before you can use it?

**Comment by pmq20** [comment] 2017-05-05 09:52
I was planning to scan and statically link all native modules during compile time (theoretically it is totally feasible), but failed to find time to do it. I'll implement it as soon as possible. Thanks for the feedback!

**Comment by pmq20** [comment] 2017-05-12 09:49
@mauron85 Native modules are starting to work on the `master` branch, if you are in a hurry you could clone the repo and run `nodec` from `master` to try it. I'll release it once I have tested it throughly.

![image](https://cloud.githubusercontent.com/assets/13315/25993055/48f39a14-373b-11e7-95cc-fc9a6951c84d.png)

**Comment by pmq20** [comment] 2017-06-05 09:22
Node.js Compiler v1.0.0 released! Native C++ modules are fully supported now.

https://github.com/pmq20/node-compiler/releases/tag/v1.0.0

@mauron85 Could you have a try and let me know if it works for you? Thanks!

**Comment by firrae** [comment] 2017-06-05 14:16
Hey @pmq20,

I just tried this out on an application I'm working on. It says it built but throws:
```
return process.dlopen(module, path._makeLong(filename));
                 ^
Error: dlopen(/__enclose_io_memfs__/node_modules/bcrypt/lib/binding/bcrypt_lib.node, 1): image not found
```

Seems like bcrypt wasn't built/included into the build? Is this an error or potentially something I did wrong? I have Node 8 installed on my Macbook and am using V1.0.0.

**Comment by firrae** [comment] 2017-06-05 14:23
To note I also get a number of `../deps/libsquash/sample/enclose_io_common.h:38:28: warning: variadic macros are a C99 feature [-Wvariadic-macros]` in the build process. ex:

`../deps/libsquash/sample/enclose_io_common.h:40:29: warning: variadic macros are a C99 feature [-Wvariadic-macros]`

`../deps/libsquash/sample/enclose_io_common.h:49:22: warning: variadic macros are a C99 feature [-Wvariadic-macros]`

Could this be related?

**Comment by ptusch** [comment] 2017-06-06 15:27
I tried this as well with [sqlite3](https://www.npmjs.com/package/sqlite3) with issues as well:
```
/Release/obj.target/openssl/deps/openssl/openssl/crypto/cpt_err.o ../deps/openssl/openssl/crypto/cpt_err.c
deps/libsquash/enclose_io_libsquash.target.mk:97: recipe for target '/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.o' failed
make[1]: *** [/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm c2142693082db8da77c35c9808dbcddd987ca620.intermediate
Makefile:76: recipe for target 'node' failed
make: *** [node] Error 2
Failed running ["make -j4"]
```

My index.js I'm trying to compile:
```js
console.log(process.version)

var knex = require('knex')({
  dialect: 'sqlite3',
  connection: {
    filename: './data.db'
  }
});

// Create a table
knex.schema.createTableIfNotExists('users', function(table) {
  table.increments('id');
  table.string('user_name');
})

// ...and another
.createTableIfNotExists('accounts', function(table) {
  table.increments('id');
  table.string('account_name');
  table.integer('user_id').unsigned().references('users.id');
})

// Then query the table...
.then(function() {
  return knex.insert({user_name: 'Tim'}).into('users');
})

// ...and using the insert id, insert into the other table.
.then(function(rows) {
  return knex.table('accounts').insert({account_name: 'knex', user_id: rows[0]});
})

// Query both of the rows.
.then(function() {
  return knex('users')
    .join('accounts', 'users.id', 'accounts.user_id')
    .select('users.user_name as user', 'accounts.account_name as account');
})

// .map over the results
.map(function(row) {
  console.log(row);
})

// Finally, add a .catch handler for the promise chain
.catch(function(e) {
  console.error(e);
})
.finally(() => {
  return knex.destroy();
});
```

I'm using nvm with node8.
I used the fresh nodec@1.0.0

Compiling normal packages works nicely.

**Comment by pmq20** [comment] 2017-06-09 10:47
@firrae I failed to reproduce this on my local machine. See the screenshot. Could you check your build log to see if some error occurs when building `bcrypt`?

![image](https://user-images.githubusercontent.com/13315/26972359-0dfacea4-4d44-11e7-933d-793d76b4aab6.png)

**Comment by pmq20** [comment] 2017-06-09 10:47
@ptusch Do you have more message regarding this particular failure:

```
deps/libsquash/enclose_io_libsquash.target.mk:97: recipe for target '/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.o' failed
```

The error message is too much truncated for a diagnosis.

**Comment by pmq20** [comment] 2017-06-09 10:54
[Also, have you cleaned your temporary directory that the compiler uses? If old directory generated by nodec 0.x is used then it would be problematic. I should fix this this in a precautionary way.

**Comment by ptusch** [comment] 2017-06-09 11:59
@pmq20 Please forgive me, I think I forgot to add sqlite3 to the package.json.
I just reinstalled and everything went as expected.

Well done btw!

**Comment by firrae** [comment] 2017-06-09 13:17
@pmq20 where would the cache be? I had used nodec before the latest version so that may be it. I'm digging around to see if I can find it on my own.

**Comment by firrae** [comment] 2017-06-09 13:42
@pmq20 nevermind, I see it's a command line option. Rebuild seems to have worked well. Now I just need to figure out the sequence of flags needed to include our public folder and it looks like it'll work. This is awesome. Thanks!

**Comment by lexor90** [comment] 2017-06-14 11:29
Closing this as native modules support has been added in v1.0.0. 
Feel free to re-open it should you need it

**Closed by lexor90** 2017-06-14 11:29 UTC
