### ISSUE TITLE
Error when using with with uws

### ISSUE THREAD

**Issue by chintan39** [pmq20/node-compiler#29] opened 2017-05-10 08:31 UTC
uws uses native add ons for websockets

"Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'"
at native (/enclose_io_memfs/node_modules/uws/uws.js:38:19)
at Object. (/enclose_io_memfs/node_modules/uws/uws.js:42:3)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object. (/enclose_io_memfs/main.js:11:23)

https://github.com/uWebSockets/uWebSockets/issues/595

**Comment by pmq20** [comment] 2017-05-10 08:37
Thanks for reporting. Could you give me a series of steps to reproduce the problem on my local machine? I would definitely fix it once reproduced.

**Comment by chintan39** [comment] 2017-05-10 08:43
1. Create a new project 
2. install uws
3. Try one of the examples of uws 
    https://github.com/uWebSockets/bindings/blob/master/nodejs/examples/test.js

And then in the project folder I ran the command `./nodec test.js`

**Comment by And-re** [comment] 2017-05-10 09:12
I have exactly the same problem.

The only workaround I found to successfully run my server app was to replace uws with ws but it is supposed to be slower so it's not a real solution for my problem.

I tried to use pkg as well but there is a problem with dynamic require statements in some node_modules so node-compiler seems to be the best tool in my case (only support for uws is missing)

I also tried using something like `--npm-package=uws --npm-package-version=0.14.1` but I get `No binaries detected inside node_modules/uws/package.json.` error.

@pmq20 is there an easy way to use cross-compilation on MacOS to generate an exe file for Windows using `nodec`?

**Comment by pmq20** [comment] 2017-05-12 03:33
@And-re I have not looked into cross-compilation yet. I personally use my Windows 7 box with Visual Studio 2015 to generate the exe.

**Comment by pmq20** [comment] 2017-05-12 03:34
@And-re I am looking into the problem with `uws`. Will reply soon.

**Comment by pmq20** [comment] 2017-05-12 03:41
@And-re Just to give a quick note that `uws` as a npm package alone does not seem to contain any binaries indeed, so the error about `No binaries detected inside node_modules/uws/package.json. error.` does not seem to be a bug.

**Comment by And-re** [comment] 2017-05-12 07:07
@pmq20 Thanks for the replies. I'm really excited for the support for `uws`.

Do you think that 500MB executable file on MacOS is normal in case of a game that takes less than 250MB with all the node_modules and assets?

**Comment by pmq20** [comment] 2017-05-12 09:59
@chintan39 Hmm....Native modules are starting to work on the `master` branch, if you are urgent you could clone the repo and run `nodec` from `master` to try it. I'll release it once I have tested it throughly.

![image](https://cloud.githubusercontent.com/assets/13315/25993471/aab32ce6-373c-11e7-8d3e-4afda38cd6ff.png)

![image](https://cloud.githubusercontent.com/assets/13315/25993486/b55398fc-373c-11e7-8f95-883cfaaa5a0c.png)

**Comment by pmq20** [comment] 2017-05-12 10:01
@And-re I'm confused. Where'd the other half of 500MB go?

**Comment by And-re** [comment] 2017-05-12 12:02
@pmq20 Ok, I will try the master branch today.
I don't know, the game itself takes 250MB and I'm also wondering what takes the rest space (Node.js environment?)

**Comment by And-re** [comment] 2017-05-12 19:46
@pmq20 It seems to work, great job! 
And suddenly the executable file is only 93.5MB :O but I have to include one "public" folder (with html, css, images, sounds) along the executable file.
Is there any way to move that folder inside the executable file?

**Comment by And-re** [comment] 2017-05-13 21:08
@pmq20 so I tried to use the master branch of node-compiler on Windows and it failed (I was trying many times and also cleaning the tmp directory):
https://gist.github.com/And-re/9f6928915b24688bed59e3fd89a4da27
![node-compiler master](https://cloud.githubusercontent.com/assets/328414/26029237/bb036f4e-3830-11e7-8921-126b306532bd.png)

When I used the 0.9.6 version for Windows it compiled successfully but there was that error with `uws` when I tried to run the exe file.
![node-compiler 0 9 6](https://cloud.githubusercontent.com/assets/328414/26029264/06a3267e-3831-11e7-90d7-7b8ff3638299.png)

**Comment by pmq20** [comment] 2017-05-15 02:30
@And-re Oops, I have not tried win32 yet. Let me fix it right away. Thanks for reporting.

**Comment by pmq20** [comment] 2017-05-15 02:31
@And-re Regarding `93.5MB`, you could go to `your_tmp_dir/__work_dir__/__enclose_io_memfs__` and check if any unwanted files are included. Common pitfall is that `a.out` is accidentally included.

**Comment by And-re** [comment] 2017-05-15 07:38
@pmq20 yes, I realized that I had a file like a.out accidentally included.

So I was using ruby to run the nodec file from the master branch like this:
`ruby ..\node-compiler\bin\nodec --tmpdir="C:\Users\And_re\hax-tmp" dist\server\server.js`

How do you generate the nodec.exe file and will it be much faster if I generate the nodec.exe once and use it instead of running ruby?

**Comment by pmq20** [comment] 2017-05-16 03:01
@And-re I generated `nodec.exe` file via [Ruby Compiler](https://github.com/pmq20/ruby-compiler), a less mature project that I was working on in my spare time.

It won't be faster. If you want to make it fast to compile maybe trying out `ccache`(https://ccache.samba.org/manual.html). Or reusing the `--tmpdir` directory, but be aware to keep it in sync with the changes from `master`.

**Comment by And-re** [comment] 2017-05-16 07:54
@pmq20 ok, I see.
So if I change one file in my project and try to reuse the `tmpdir` from last time the change won't be reflected? Can I just copy that file manually to `your_tmp_dir/__work_dir__/__enclose_io_memfs__` and reuse the rest of the files in the `tmpdir`?

**Comment by pmq20** [comment] 2017-05-17 03:21
@And-re Changes in your project WILL be reflected. Changes in Node.js Compiler itself WILL NOT.

**Comment by And-re** [comment] 2017-05-25 18:54
@pmq20 Is it ok to try the version for Windows right now or are there still some issues?

**Comment by pmq20** [comment] 2017-05-26 03:03
@And-re there are still some issues as the CI is not green yet. I'm working on it

**Comment by And-re** [comment] 2017-05-26 06:08
@pmq20 ok, thank you and good luck :)

**Comment by pmq20** [comment] 2017-06-05 09:18
Node.js Compiler v1.0.0 released! C++ modules are fully supported now.

https://github.com/pmq20/node-compiler/releases/tag/v1.0.0

@And-re @chintan39 Could you have a try and let me know if it works for you? Thanks!

**Comment by And-re** [comment] 2017-06-05 18:39
@pmq20 With node 8 I have problems to run my project (after `rm -rf node_modules` and `npm i` or `yarn`).  With node 7.10 everything works.
And when I finally managed to compile my project (after problems with `vcbuild.bat`) I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/328414/26797920/ef4f3584-4a2e-11e7-9f5b-5160e9eeef9f.png)
(in the meantime I renamed the executable file)

**Comment by pmq20** [comment] 2017-06-09 10:44
@And-re I failed to reproduce this on my local win32 machine. See the screen-shot. Could you give me a project or minimized project to reproduce the error? Thanks.

![1](https://user-images.githubusercontent.com/13315/26972283-ac114b28-4d43-11e7-9c02-2be06d1aede7.png)

**Comment by pmq20** [comment] 2017-06-09 10:56
@And-re Also, have you cleaned your temporary directory that the compiler uses? If old directory generated by nodec 0.x is used then it would be problematic. It needs to be cleaned when a compiler of a new version is used. I should fix this in a precautionary way: https://github.com/pmq20/node-compiler/issues/42

**Comment by And-re** [comment] 2017-06-09 11:57
@pmq20 Ok, I'm using win64 and I will try to prepare a reproducable example.
Yes, everything was generated using node-compiler 1.0.0. The only problem was that I was out of heap memory 2 times and had to retry 2 times even thought I have over 8000MB of virtual memory set as you described it in another issue on github.

**Comment by And-re** [comment] 2017-06-09 18:44
@pmq20 so it looks like the problem is with npm 5. Node 8 isn't a problem here.
When I use yarn:
![image](https://user-images.githubusercontent.com/328414/26989569-e06c182a-4d53-11e7-92da-85b7ee06bf6e.png)
When I use npm:
![image](https://user-images.githubusercontent.com/328414/26989628-1d442350-4d54-11e7-8a8c-76b3f562596a.png)

**Comment by pmq20** [comment] 2017-06-10 12:21
@And-re 

Using x64 toolchain could also help eliminate the insufficient-memory problem. Microsoft x64 cl.exe (or even x64_x86 cross tool-chain) will not throw this error when x86 tools throw, based on my experiments.

**Comment by pmq20** [comment] 2017-06-10 12:22
@And-re You could also try use the "--npm=..." option to opt out npm.

**Comment by chintan39** [comment] 2017-06-22 13:55
@pmq20 Tried the latest version 1.1.0 , works well now 🎉

**Comment by lexor90** [comment] 2017-06-28 16:46
Closing this as it has been fixed. Feel free to re-open this ticket should you need it.

**Closed by lexor90** 2017-06-28 16:46 UTC

**Comment by CoolHandLuke88** [comment] 2018-01-15 09:59
I ran into this exact issue.
I wanted to leave this here for anyone else that may run into this issue with docker and `uws` installation.

Hope you guys don't mind I drop this here.

In Dockerfile
*********************************
`FROM node:8.9-alpine`

`RUN apk add --update \`
    `libc6-compat`

*********************************
Needed `libc6-compact`

This should resolve the issue seen below.

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
